version: '3.7'


services:
  database:
    image: "postgres:11"
    environment:
      POSTGRES_USER: omero
      POSTGRES_DB: omero
      POSTGRES_PASSWORD: omero
  db:
    environment:
      POSTGRES_MULTIPLE_DATABASES: omero_db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: fostgres
    image: jhnnsrs/daten:next
    labels:
      - "arkitekt.default.service=db"
  konviktion_server:
    build: .
    ports:
    - 8888:80
    labels:
      - "arkitekt.default.service=konviktion_server"
      - "traefik.enable=true"
      - "traefik.http.routers.mikro.entrypoints=konviktion_server"
      - "traefik.http.routers.mikro.rule=Host(`jhnnsrs-server.hyena-sole.ts.net`)"
      - "traefik.http.services.mikro.loadbalancer.server.port=8080"
      - "traefik.http.routers.mikro.tls.certresolver=myresolver"
  redis:
    image: redis:latest
    labels:
      - "arkitekt.default.service=redis"

